[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
target-version = "py39"

line-length = 130

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10