name: Backend Deploy CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Depoly to Ali Server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_USER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker exec backend sh -c "cd /SE/backend && git pull origin main"
            